<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Shared\PEIA.Shared.Infra\PEIA.Shared.Infra.csproj" />
    <ProjectReference Include="..\Modules\PEIA.Modules.ERP\PEIA.Modules.ERP.csproj" />
    <ProjectReference Include="..\Modules\PEIA.Modules.Inventory\PEIA.Modules.Inventory.csproj" />
    <ProjectReference Include="..\Modules\PEIA.Modules.Logistics\PEIA.Modules.Logistics.csproj" />
    <ProjectReference Include="..\Modules\PEIA.Modules.Reports\PEIA.Modules.Reports.csproj" />
    <ProjectReference Include="..\Modules\PEIA.Modules.Automation\PEIA.Modules.Automation.csproj" />
    <ProjectReference Include="..\Modules\PEIA.Modules.Prediction\PEIA.Modules.Prediction.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
