// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PEIA.Shared.Infra.Data;

#nullable disable

namespace PEIA.Shared.Infra.Migrations
{
    [DbContext(typeof(PeiaDbContext))]
    [Migration("20260721190000_AddCapturasTable")]
    partial class AddCapturasTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PEIA.Shared.Infra.Cameras.Captura", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<int>("CameraId")
                    .HasColumnType("integer");

                b.Property<string>("Descripcion")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<DateTime>("FechaCaptura")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("ImagenUrl")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<string>("NombreCamara")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<string>("Zona")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.Property<Guid?>("UsuarioId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("FechaCaptura");

                b.ToTable("Capturas", (string)null);
            });
#pragma warning restore 612, 618
        }
    }
}
