-- =============================================================================
--  PEIA - Script de migración inicial (PostgreSQL) - VERSIÓN ENDURECIDA
-- =============================================================================
--  Objetivos de robustez ("indestructible") y soporte de concurrencia
--  (varios procesos / múltiples instancias atacando la misma BD):
--
--   1. ATÓMICO         : todo el DDL corre en una sola transacción. Si algo
--                        falla, NO queda nada a medias (DDL transaccional de PG).
--   2. IDEMPOTENTE     : el script se puede re-ejecutar sin error. Sirve tanto
--                        para una BD vacía como para una donde EF Core ya creó
--                        las tablas (despliegues repetidos / reintentos).
--   3. CONCURRENCIA    : se ARREGLA el token de concurrencia optimista de
--                        "Centros". El mapeo IsRowVersion() -> bytea NO se
--                        autoincrementa en PostgreSQL (a diferencia de SQL
--                        Server), por lo que tal cual venía generado las
--                        actualizaciones concurrentes se pisaban entre sí
--                        (lost updates). Aquí un trigger BEFORE INSERT/UPDATE
--                        regenera "Version" en cada escritura -> EF detecta el
--                        conflicto y lanza DbUpdateConcurrencyException.
--   4. INTEGRIDAD      : defaults a nivel servidor (gen_random_uuid(), now()),
--                        CHECK constraints y unicidad de email/usuario para que
--                        la BD se defienda incluso ante inserciones por fuera de
--                        la aplicación.
--
--  Compatible con EF Core: se conservan exactamente los nombres de tablas,
--  columnas, claves e índices, y la fila de __EFMigrationsHistory.
-- =============================================================================

-- gen_random_uuid() / gen_random_bytes() (núcleo en PG13+, aquí por compatibilidad)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

START TRANSACTION;

-- -----------------------------------------------------------------------------
--  Historial de migraciones de EF Core
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- -----------------------------------------------------------------------------
--  Tablas (IF NOT EXISTS -> seguras para BD nueva o ya migrada)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Centros" (
    "Id" uuid NOT NULL,
    "Nombre" character varying(100) NOT NULL,
    "Codigo" character varying(20) NOT NULL,
    "Direccion" character varying(300) NOT NULL,
    "Activo" boolean NOT NULL,
    "Version" bytea,
    CONSTRAINT "PK_Centros" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Roles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "Usuarios" (
    "Id" uuid NOT NULL,
    "NombreCompleto" character varying(200) NOT NULL,
    "Activo" boolean NOT NULL,
    "FechaCreacion" timestamp with time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Usuarios" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_Usuarios_UserId" FOREIGN KEY ("UserId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_Usuarios_UserId" FOREIGN KEY ("UserId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_Usuarios_UserId" FOREIGN KEY ("UserId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "AspNetUserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_Usuarios_UserId" FOREIGN KEY ("UserId") REFERENCES "Usuarios" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "UsuarioCentros" (
    "UsuarioId" uuid NOT NULL,
    "CentroId" uuid NOT NULL,
    "Activo" boolean NOT NULL,
    CONSTRAINT "PK_UsuarioCentros" PRIMARY KEY ("UsuarioId", "CentroId"),
    CONSTRAINT "FK_UsuarioCentros_Centros_CentroId" FOREIGN KEY ("CentroId") REFERENCES "Centros" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_UsuarioCentros_Usuarios_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuarios" ("Id") ON DELETE RESTRICT
);

-- -----------------------------------------------------------------------------
--  Índices (todos IF NOT EXISTS para re-ejecución segura)
-- -----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");
CREATE UNIQUE INDEX IF NOT EXISTS "IX_Centros_Codigo" ON "Centros" ("Codigo");
CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex" ON "Roles" ("NormalizedName");
CREATE INDEX IF NOT EXISTS "IX_UsuarioCentros_CentroId" ON "UsuarioCentros" ("CentroId");
CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex" ON "Usuarios" ("NormalizedUserName");

-- Índice parcial: la mayoría de los listados filtran por centros/usuarios activos.
CREATE INDEX IF NOT EXISTS "IX_Centros_Activo" ON "Centros" ("Activo") WHERE "Activo";
CREATE INDEX IF NOT EXISTS "IX_UsuarioCentros_Activo"
    ON "UsuarioCentros" ("UsuarioId", "CentroId") WHERE "Activo";

-- =============================================================================
--  ENDURECIMIENTO (aplica tanto a BD nueva como a una ya creada por EF Core)
-- =============================================================================

-- -----------------------------------------------------------------------------
--  1) Defaults a nivel servidor: la BD genera valores válidos aunque la
--     inserción venga por fuera de la app (scripts, ETL, otra instancia).
-- -----------------------------------------------------------------------------
ALTER TABLE "Centros"  ALTER COLUMN "Id"        SET DEFAULT gen_random_uuid();
ALTER TABLE "Centros"  ALTER COLUMN "Activo"    SET DEFAULT TRUE;
ALTER TABLE "Roles"    ALTER COLUMN "Id"        SET DEFAULT gen_random_uuid();
ALTER TABLE "Usuarios" ALTER COLUMN "Id"            SET DEFAULT gen_random_uuid();
ALTER TABLE "Usuarios" ALTER COLUMN "Activo"        SET DEFAULT TRUE;
ALTER TABLE "Usuarios" ALTER COLUMN "FechaCreacion" SET DEFAULT now();
ALTER TABLE "Usuarios" ALTER COLUMN "EmailConfirmed"       SET DEFAULT FALSE;
ALTER TABLE "Usuarios" ALTER COLUMN "PhoneNumberConfirmed" SET DEFAULT FALSE;
ALTER TABLE "Usuarios" ALTER COLUMN "TwoFactorEnabled"     SET DEFAULT FALSE;
ALTER TABLE "Usuarios" ALTER COLUMN "LockoutEnabled"       SET DEFAULT TRUE;
ALTER TABLE "Usuarios" ALTER COLUMN "AccessFailedCount"    SET DEFAULT 0;
ALTER TABLE "UsuarioCentros" ALTER COLUMN "Activo" SET DEFAULT TRUE;

-- -----------------------------------------------------------------------------
--  2) CHECK constraints (idempotentes vía pg_constraint).
-- -----------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CK_Centros_Nombre_NoVacio') THEN
        ALTER TABLE "Centros" ADD CONSTRAINT "CK_Centros_Nombre_NoVacio"
            CHECK (length(btrim("Nombre")) > 0);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CK_Centros_Codigo_NoVacio') THEN
        ALTER TABLE "Centros" ADD CONSTRAINT "CK_Centros_Codigo_NoVacio"
            CHECK (length(btrim("Codigo")) > 0);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CK_Usuarios_NombreCompleto_NoVacio') THEN
        ALTER TABLE "Usuarios" ADD CONSTRAINT "CK_Usuarios_NombreCompleto_NoVacio"
            CHECK (length(btrim("NombreCompleto")) > 0);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CK_Usuarios_AccessFailedCount_NoNegativo') THEN
        ALTER TABLE "Usuarios" ADD CONSTRAINT "CK_Usuarios_AccessFailedCount_NoNegativo"
            CHECK ("AccessFailedCount" >= 0);
    END IF;
END $$;

-- -----------------------------------------------------------------------------
--  3) Unicidad de email a nivel BD.
--     Program.cs activa options.User.RequireUniqueEmail = true; aquí lo
--     hacemos cumplir también en la BD. (Los NULL no colisionan en PG, por lo
--     que se permiten varios usuarios sin email, igual que ASP.NET Identity.)
-- -----------------------------------------------------------------------------
DROP INDEX IF EXISTS "EmailIndex";
CREATE UNIQUE INDEX IF NOT EXISTS "EmailIndex" ON "Usuarios" ("NormalizedEmail");

-- -----------------------------------------------------------------------------
--  4) CONCURRENCIA OPTIMISTA REAL para "Centros".
--
--     El token "Version" (bytea, mapeado con IsRowVersion()) NO cambia solo en
--     PostgreSQL. Sin esto, dos procesos que editan el mismo Centro se pisan.
--     Con este trigger, cada INSERT/UPDATE asigna un valor nuevo y monótono;
--     EF Core compara el valor original en el WHERE de UPDATE: si otro proceso
--     ya lo cambió, afecta 0 filas y lanza DbUpdateConcurrencyException.
-- -----------------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS "peia_row_version_seq" AS bigint;

CREATE OR REPLACE FUNCTION "peia_set_row_version"()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    -- int8send -> 8 bytes big-endian; siempre distinto y creciente.
    NEW."Version" := int8send(nextval('"peia_row_version_seq"'));
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS "trg_Centros_RowVersion" ON "Centros";
CREATE TRIGGER "trg_Centros_RowVersion"
    BEFORE INSERT OR UPDATE ON "Centros"
    FOR EACH ROW
    EXECUTE FUNCTION "peia_set_row_version"();

-- Backfill: cualquier fila existente con Version NULL queda con token válido.
UPDATE "Centros" SET "Version" = int8send(nextval('"peia_row_version_seq"'))
WHERE "Version" IS NULL;

-- -----------------------------------------------------------------------------
--  Registrar la migración (idempotente: no duplica si ya está aplicada).
-- -----------------------------------------------------------------------------
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260630204415_InitialCreate', '8.0.0')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;

-- -----------------------------------------------------------------------------
--  5) Seed de Usuarios (Contrase�a por defecto: Peia2025!)
-- -----------------------------------------------------------------------------
INSERT INTO ""Usuarios"" (""Id"", ""UserName"", ""NormalizedUserName"", ""Email"", ""NormalizedEmail"", ""EmailConfirmed"", ""PasswordHash"", ""SecurityStamp"", ""ConcurrencyStamp"", ""PhoneNumber"", ""PhoneNumberConfirmed"", ""TwoFactorEnabled"", ""LockoutEnd"", ""LockoutEnabled"", ""AccessFailedCount"", ""NombreCompleto"", ""Activo"", ""FechaCreacion"")
VALUES 
(gen_random_uuid(), 'admin', 'ADMIN', 'admin@peia.com', 'ADMIN@PEIA.COM', true, 'AQAAAAIAAYagAAAAEO6ucb4C9UZznamjuC5AtUXow1Mbn5YoEtBkb+bV8LYqxpZ0HAJ8roru0bgWxWC9Jg==', 'Z1234567890', gen_random_uuid()::text, null, false, false, null, true, 0, 'Ariel Guevara', true, now()),
(gen_random_uuid(), 'inventario', 'INVENTARIO', 'inventario@peia.com', 'INVENTARIO@PEIA.COM', true, 'AQAAAAIAAYagAAAAEKnys8ssdfqPT9CN3D/ADH90Raowa/9thKJUDvqDDdhDGGgUWfS23HkKRVZuvyQvDA==', 'Z1234567890', gen_random_uuid()::text, null, false, false, null, true, 0, 'Julian Sierra', true, now()),
(gen_random_uuid(), 'logistica', 'LOGISTICA', 'logistica@peia.com', 'LOGISTICA@PEIA.COM', true, 'AQAAAAIAAYagAAAAEBTBx8NSwfmYSwQNxIdDcFfslr7KDMRiTX7PfRcqOYAjtZVP22tfnTfLUJ4EJvDHkw==', 'Z1234567890', gen_random_uuid()::text, null, false, false, null, true, 0, 'Jose Villa', true, now()),
(gen_random_uuid(), 'reportes', 'REPORTES', 'reportes@peia.com', 'REPORTES@PEIA.COM', true, 'AQAAAAIAAYagAAAAEMRjdirXU/hCAIbrqsAtZrTQzxcW6BX99OozxbJ/anOn2Kd15rUwPN9hg39hVT91GQ==', 'Z1234567890', gen_random_uuid()::text, null, false, false, null, true, 0, 'Jennifer Munoz', true, now()),
(gen_random_uuid(), 'supervisor', 'SUPERVISOR', 'supervisor@peia.com', 'SUPERVISOR@PEIA.COM', true, 'AQAAAAIAAYagAAAAEC+J9JeQVVEl3tOyqmRp70IhFk+dzO/bdhgER2/nYx1BLC+4/6wFqc9HvJzvVTZrag==', 'Z1234567890', gen_random_uuid()::text, null, false, false, null, true, 0, 'Mariano Sanchez', true, now())
ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
--  6) Seed de Roles y Asignaciones
-- -----------------------------------------------------------------------------
INSERT INTO ""Roles"" (""Id"", ""Name"", ""NormalizedName"", ""ConcurrencyStamp"")
VALUES 
(gen_random_uuid(), 'Administrador', 'ADMINISTRADOR', gen_random_uuid()::text),
(gen_random_uuid(), 'OperadorInventario', 'OPERADORINVENTARIO', gen_random_uuid()::text),
(gen_random_uuid(), 'Logistica', 'LOGISTICA', gen_random_uuid()::text),
(gen_random_uuid(), 'Reportes', 'REPORTES', gen_random_uuid()::text),
(gen_random_uuid(), 'Supervisor', 'SUPERVISOR', gen_random_uuid()::text)
ON CONFLICT DO NOTHING;

-- Nota: Para asignar correctamente los roles a los usuarios mediante SQL, se debe hacer un cruce de IDs.
-- Se recomienda que el SeedData de EF Core maneje esto en la primera ejecuci�n (Program.cs).

